# start of Meshtastic configure yaml
channel_url: https://meshtastic.org/e/#CgsSAQEoATABOgIIDAozCAESIGtPdW42blM5eHVUYmFIZk5MTkR1UkxpWnJmQlBrMkxDGgVrZDFtdSgBMAE6AggMEg8IATgBQANIAVAeaAHIBgE
config:
  bluetooth:
    enabled: true
    fixedPin: 111111
    mode: FIXED_PIN
  device:
    nodeInfoBroadcastSecs: 10800
    tzdef: EST5EDT,M3.2.0/2:00:00,M11.1.0/2:00:00
  display:
    screenOnSecs: 600
  lora:
    configOkToMqtt: true
    hopLimit: 3
    region: US
    sx126xRxBoostedGain: true
    txEnabled: true
    txPower: 30
    usePreset: true
  mqtt:
    encryptionEnabled: false
  network:
    enabledProtocols: 1
    ntpServer: meshtastic.pool.ntp.org
    wifiEnabled: true
    wifiPsk: IVM3D2GU52YLZ6C
    wifiSsid: HOME69-TM
  position:
    broadcastSmartMinimumDistance: 100
    broadcastSmartMinimumIntervalSecs: 30
    fixedPosition: true
    gpsMode: NOT_PRESENT
    gpsUpdateInterval: 120
    positionBroadcastSecs: 900
    positionBroadcastSmartEnabled: true
  power:
    lsSecs: 300
    minWakeSecs: 10
    sdsSecs: 4294967295
    waitBluetoothSecs: 60
  security:
    privateKey: base64:WHXmSX1eEeSeKaxBx1ShSSwfRPHWTbyK65YcLAjnomE=
    publicKey: base64:SwS/tbMyzOhZcWJy/GCIj7BeW7tB8A40cbbv3RUE5yU=
    serialEnabled: true
location:
  alt: 30
  lat: 42.345096
  lon: -71.121411
module_config:
  ambientLighting:
    blue: 56
    current: 10
    green: 224
    red: 12
  detectionSensor:
    detectionTriggerType: LOGIC_HIGH
    minimumBroadcastSecs: 45
  mqtt:
    address: mqtt.meshtastic.org
    enabled: true
    encryptionEnabled: true
    mapReportSettings:
      positionPrecision: 10
      publishIntervalSecs: 3600
      shouldReportLocation: true
    mapReportingEnabled: true
    password: large4cats
    root: msh/US
    username: meshdev
  serial:
    baud: BAUD_9600
    rxd: 34
    txd: 33
owner: KD1MU Radio
owner_short: KDMU
